### ISSUE TITLE
Mysql pool table does not update

### ISSUE THREAD

**Issue by firework09** [moopless/stratum-mining-litecoin#11]
Subj. Update made only when daemon restart, when he runned no changes in fields height, balance, etc. Also workers which autocreated after daemon starts does not show. But they appear after restart.

I dont make any changes in config file on cache db and wait about 2 hours.

Html table rows on 8889 port is red.

Connect to litecoind established ofcourse, because sqlite works fine ;)

**Comment by firework09** [comment]
But on sqlite without workers, for example, field 'height' on 'pool' table
updated from litecoind regularly and on mysql not updated while daemon does
not restarted manually.

I create workers by API or by cgminer - does not matter.

2013/6/12 Sebastian Grewe notifications@github.com

**Comment by moopless** [comment]
What configuration options are you using for stratum-mining-litecoin? Which database version are you using? 

Since you mention the pool table I can only assume that you are using the extended database. This database was added back in to keep the original features. Unfortunately the tables are different from the pushpool standard so I added them back in in cause users preferred not to use mmcfe-ng, since mmcfe-ng/mmcfe should be doing all of the stats and user management. 

The extended database version is not compatible with mmcfe-ng.. DATABASE_EXTEND should be false when using mmcfe-ng and the default database layout should be used for mysql.  USERS_AUTOADD should work, but it is better to leave the creation of the users to the user management software (mmcfe-ng).

**Comment by moopless** [comment]
Any more information on this ticket?

**Comment by Neozonz** [comment]
@firework09 Please update ticket or we will close this issue.

Thanks

**Comment by moopless** [comment]
No response. Closing as wont fix.
