### ISSUE TITLE
Modify Stratum subver

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#16]
Is it possible to change the subversion of stratum?
I know of another pool that changes this value to signify the mining daemon... can't find any information on how to go about to change it though.

litecoind getpeerinfo
    {
        "addr" : "86.148.38.52:9333",
        "services" : "00000001",
        "lastsend" : 1371167664,
        "lastrecv" : 1371167554,
        "conntime" : 1371161440,
        "version" : 60001,
        "subver" : "/Satoshi:0.6.3/",             <---------------------------------
        "inbound" : false,
        "releasetime" : 0,
        "startingheight" : 370451,
        "banscore" : 0
    }

It would help debug connection issues if the subver tag was different from normal litecoind clients

**Comment by Neozonz** [comment]
Found more info here

https://en.bitcoin.it/wiki/BIP_0014

**Comment by moopless** [comment]
This is implemented as a part of [litecoind](https://github.com/litecoin-project/litecoin). You could change it there and recompile litecoind. IIRC you can change it in src/version.cpp CLIENT_NAME or CLIENT_VERSION. I don't know the code base enough to comment, but I think its generic so that its hard to target a peer. Below is the comment in src/version.cpp.

> // Name of client reported in the 'version' message. Report the same name
> // for both bitcoind and bitcoin-qt, to make it harder for attackers to
> // target servers or GUI users specifically.

Since this is out of the scope of stratum-mining I will close this issue.
