### ISSUE TITLE
Does it work for POS-like coins (NovaCoin)?

### ISSUE THREAD

**Issue by feeleep75** [moopless/stratum-mining-litecoin#22]
Also - can it be modified to work with scrypt-jane coins (YaCoin)?

**Comment by moopless** [comment]
It should work for any scrypt based coins. I have tried multiple alt coins with great success. 

Some of the alt coins (like megacoin) do not implement **getblocktemplate** and they will need some basic stratum-mining-litecoin modifications. Specifically they need to use **submitblock** instead of **getblocktemplate** in _lib/bitcoin_rpc.py_ and probably a modification in _mining/**init**.py_. This should only be coins that are far behind in development. 

For scrypt-jane, you may have to make a few modifications, but I can not speak to that. You would have to import scrypt-jane and maybe change the PoW functions. Fork it and give it a try. 

For low difficulty coins you may run into issue #21, which I should have a fix/workaround tonight if the internet on the train works.
