### ISSUE TITLE
Upstream_result not filled

### ISSUE THREAD

**Issue by JohnDorien1** [moopless/stratum-mining-litecoin#30]
I am using this in combination with mmcfe-ng. The field upstram_result in in table shares never gets filled, whereas seems to be the reason i don't have proper block statistics in the front end.
I cannot find any log (neither stratum not apache nor mmcfe-ng) telling me fail in insert.

**Comment by TheSerapher** [comment]
God I am stupid. Saw a notification and thought it was `mmcfe-ng` based. Purged my silly comment and re-opening so others can deal with it :D

**Comment by JohnDorien1** [comment]
Noch kein Kaffee? :)
Please re-insert the first comment you made as it is leading the right direction.
Some blocks were found so this is ok, but e.g. block finder and confirmations left is not filled with information, as far as i understand the debug output it is because the upstream_result is empty (NULL, so default).

**Comment by TheSerapher** [comment]
Upstream accepted shares that are indicating a block was found need to be flagged as `upstream_result = Y` in the DB by the pool software. Maybe the recent changes of checking a block header with the solution stored in the DB is not working properly, hence no shares are marked accepted by upstream.

Please confirm you have found blocks that are not showing any `upstream_result` shares. Should help in further debugging.

**Comment by moopless** [comment]
Is this on a PoS coin? I think this is because they changed the block hash to scrypt. A patch for this is in https://github.com/moopless/stratum-mining-litecoin/issues/26#issuecomment-20238402.

I just pushed 15296fd to resolve the issue. Please pull the new changes and let me know if it is working. I am closing this as a duplicate so we can track all of the progress in #26

**Comment by obigal** [comment]
Although rare I've seen this as well, with some recent changes if even 1 'Y' is missing every block finder after will fail, I've had to implement an ugly hack that makes 3 attempts to find the share then if not found marks a share closest to the block find time 'Y' so miners never miss a block find payout and so the rest of the blocks can continue on.

**Comment by moopless** [comment]
@obigal Do you have any logs? What happens if you get rid of the _blockexists_ check in _bitcoin_rpc.py_?

```
--- a/lib/bitcoin_rpc.py
+++ b/lib/bitcoin_rpc.py
@@ -45,7 +45,7 @@ class BitcoinRPC(object):
         #resp = (yield self._call('getblocktemplate', [{'mode': 'submit', 'data': block_hex}]))
         if json.loads(resp)['result'] == None:
             # make sure the block was created.
-            defer.returnValue((yield self.blockexists(block_hash_hex))) 
+            defer.returnValue(True)
         else:
             defer.returnValue(False)
```

If it submits any coins, that means the way we are building the block header is correct, so we should be able to continue to submit blocks. I would suspect that if it fails after a the first valid block, we would see a stack trace. Can you run it with:

```
twistd -ny launcher.tac -l debug.log
```

That should log it to debug.log. Can you send the debug.log? Or at least the sections around the "candidate" in that log and _stratum.log_?

Let's track this ticker over in #26. I'll put the same information over there.

**Comment by obigal** [comment]
I haven't seen it happen for a while now, this was before blockexists was added, unfortunately I never logged any of the missing 'Y' shares, I have throw in some logging to see when and why this might happen.
