### ISSUE TITLE
Processing of Message failed

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#31]
Getting some strange errors in my logs, see trace back.

410430519:2013-07-02 13:49:56,929 ERROR protocol protocol.dataReceived # Processing of message failed
410430612-Traceback (most recent call last):
410430648-  File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py", line 185, in dataReceived
410430769-    self.lineReceived(line, request_counter)
410430815-  File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py", line 216, in lineReceived
410430936-    raise custom_exceptions.ProtocolException("Cannot decode message '%s'" % line)

**Comment by TheSerapher** [comment]
I have those too with vips stratum ... Maybe they can be fixed? :-)

**Comment by moopless** [comment]
I think I found the problem in stratum. Is it always followed with a _connectionMade_ line?

```
DEBUG protocol protocol.connectionMade # Connected x.x.x.x
```

I think there is a null/newline at the end that it tries to decode. This raises the exception which reset the socket connection with the miner. We can suppress the exception or ensure the string is not null. Either way we would do exactly what the catch block does (without throwing the exception). It is out of the scope of this project, so I cannot include a fix in my code, but I think we can make some easy modifications to stratum. 

I added the following line to _/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py:176_ and have not seen the stack trace since.

```
lines = filter(None, lines)
```

Anyone want to give it a try?

**Comment by Neozonz** [comment]
Will once home

**Comment by Neozonz** [comment]
Added to line 176-

Still seeing issues

2013-07-02 21:30:05,291 ERROR protocol protocol.dataReceived # Processing of message failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py", line 187, in dataReceived
    self.lineReceived(line, request_counter)
  File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py", line 218, in lineReceived
    raise custom_exceptions.ProtocolException("Cannot decode message '%s'" % line)
'rotocolException: Cannot decode message 'POST / HTTP/1.1

**Comment by Neozonz** [comment]
Could this issue be because someone is connecting to stratum via a browser?
 "POST / HTTP/1.1"

**Comment by moopless** [comment]
Yeah. The it sounds like the socket does not know how to translate the HTTP header.
