### ISSUE TITLE
Document supported and/or recommended versions of stratum-mining-litecoin dependencies

### ISSUE THREAD

**Issue by ilya-stromberg** [moopless/stratum-mining-litecoin#47]
You write in README.md file list of dependencies, but without a versions.
As I can see, we have to use Twisted >= 11.1. So, which Twisted version is recommended?

Also, please document the OS and version in the INSTALL.md file. It looks like Ubuntu installation, but with version?

Another question: do you use any specific features of the Python 2.7?
Twisted and Stratum support Python 2.6 and Python 2.7.
litecoin_scrypt doesn't document supported Python versions, but it written in C and uses Python only for integration. It looks like that litecoin_scrypt supports Python 2.\* and Python 3.\* versions.
So, can I run the stratum-mining-litecoin via Python 2.6?

**Comment by moopless** [comment]
@ilya-stromberg I have not tested any other versions than what it on my dev server, so I have not listed the versions on there. I currently use an Ubuntu 12.04 x64 dev server, but if you have the dependencies any distro should work. By using this code, the user has the responsibility of testing it prior to running in production. My recommendation is to run a QA server and prove that the solution works before pushing changes to a production server. 

My current environment uses the following.  
- Python 2.7.3
- Python Mysqldb 1.2.3
- Python Twisted 11.1.0
- Latest Stratum Core
- Mysql 5.5.31
- Litecoind 0.6.9.2

I am not sure if python 2.6 will work or not. To be honest, I have not tried it. Since I am only maintaining the code I cannot say that the code is not using any features of 2.7, so I just made it a dependency. I see no reason that it should be incompatible with 3.0, but it will require someone to test it to make sure. 

Would you be willing to test python 2.6 to confirm compatibility?

**Comment by ilya-stromberg** [comment]
OK, I'll try the python 2.6.
Can you contact the original author of stratum-mining-litecoin to find out if it supported python 2.6?

**Comment by moopless** [comment]
I ported stratum-mining to stratum-mining-litecoin from a fork of the original https://github.com/slush0/stratum-mining. It includes the following tree, which can be found in the network, https://github.com/moopless/stratum-mining-litecoin/network/members.
1. https://github.com/slush0/stratum-mining
2. https://github.com/generalfault/stratum-mining
3. https://github.com/wadewomersley/stratum-mining
4. https://github.com/moopless/stratum-mining-litecoin

Feel free to reach out to the authors to find out if they have used Python 2.7 specific code. I do not plan on making it backwards compatible. For reference I ran https://github.com/ghewgill/pyqver/ on all of the python files in stratum-mining-litecoin and it looks like it is compatible with 2.6.

```
$ find ~/stratum-mining-litecoin/ -iname "*.py" -exec python ~/pyqver/pyqver2.py {} \; |awk '{print $1}' |sort |uniq
2.0
2.2
2.3
2.4
2.5
2.6
```

Please let us know if it does work with Python 2.6.

**Comment by moopless** [comment]
@ilya-stromberg Any update on this?

**Comment by moopless** [comment]
No update. Closing issue.
